repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort
        types: [python]
        language: python
        exclude: tests
      - id: flynt
        name: flynt
        entry: flynt
        args: [--fail-on-change]
        types: [python]
        language: python
        #      - id: black
        #name: black
        #entry: black
        #language: python
        #types: [python]
        #exclude: node_modules
      - id: yapf
        name: yapf
        entry: yapf
        args: [-i, --style, '{based_on_style: google, column_limit: 120}']
        language: python
        types: [python]
        exclude: tests
      - id: pylint
        name: pylint
        entry: pylint
        args: ["--rcfile=pylintrc", "--output-format=parseable"]
        language: python
        types: [python]
        exclude: tests
      # - id: flake8
      #   name: flake8
      #   entry: flake8
      #   language: python
      #   types: [python]
      #   exclude: tests
      # - id: bandit
      #   name: bandit
      #   entry: bandit
      #   language: python
      #   types: [python]
      #   args: [-c, pyproject.toml]
      #   exclude: ^nerf/utils/
      # - id: mypy
      #   name: mypy
      #   entry: mypy
      #   types: [python]
      #   language: python
      #   exclude: ^nerf/utils/|^tests/
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: end-of-file-fixer
        exclude: .*(min.js|min.css|html|svg|css.map|js.map)
      - id: trailing-whitespace
        exclude: .*(md)
